require("dotenv").config();

const express = require("express");
const nodemailer = require("nodemailer");
const cors = require("cors");
const multer = require("multer");
const pdfParse = require("pdf-parse/lib/pdf-parse.js");
const mammoth = require("mammoth");
const Groq = require("groq-sdk");
const https = require("https");

const app = express();
const upload = multer();
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

app.use(cors({
  origin: [
    "https://skill-gap-analyzer-delta.vercel.app",
    "http://localhost:3000"
  ],
  methods: ["GET", "POST"],
  allowedHeaders: ["Content-Type"]
}));
app.use(express.json());

// ✅ Health check BEFORE app.listen
app.get("/health", (req, res) => res.json({ status: "ok" }));

app.post("/test", (req, res) => {
  console.log("TEST HIT");
  res.json({ message: "POST working" });
});

app.post("/parse-resume", upload.single("resume"), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: "No file uploaded" });
    const filename = req.file.originalname.toLowerCase();
    let text = "";
    if (filename.endsWith(".pdf")) {
      const data = await pdfParse(req.file.buffer);
      text = data.text;
    } else if (filename.endsWith(".docx")) {
      const result = await mammoth.extractRawText({ buffer: req.file.buffer });
      text = result.value;
    } else {
      text = req.file.buffer.toString("utf-8");
    }
    text = text.replace(/\s+/g, " ").trim();
    res.json({ text, chars: text.length });
  } catch (err) {
    console.error("Parse error:", err);
    res.status(500).json({ error: "Could not parse resume" });
  }
});

app.post("/analyze", async (req, res) => {
  const { role, level, skills, experience, goals, resumeText, email } = req.body;
  if (!role || !level || !skills) {
    return res.status(400).json({ error: "role, level, and skills are required" });
  }
  try {
    const prompt = `You are an expert tech career coach. Analyze the skill gap for this person and return ONLY a valid JSON object with no markdown or explanation.

Input:
- Target Role: ${role}
- Target Level: ${level}
- Current Skills: ${skills}
- Years of Experience: ${experience || "not provided"}
- Career Goals: ${goals || "not provided"}
${resumeText ? `- Resume Text: ${resumeText.slice(0, 1500)}` : ""}

Return a JSON object with EXACTLY these fields:
{
  "readinessScore": <number 0-100>,
  "readinessLabel": <"Not Ready" | "Partially Ready" | "Almost Ready" | "Ready">,
  "atsScore": <number 0-100 or null if no resume>,
  "atsLabel": <"Weak" | "Fair" | "Good" | "Strong" or null if no resume>,
  "summary": <2-3 sentence honest assessment>,
  "topStrengths": [<string>, ...],
  "criticalGaps": [<string>, ...],
  "timeToReady": <e.g. "3-6 months">,
  "salaryImpact": <e.g. "+$15,000 - $25,000">,
  "skills": [{"name": <string>, "current": <0-10>, "target": <0-10>, "insight": <string>}, ...],
  "atsFeedback": [{"category": <string>, "score": <0-100>, "feedback": <string>}, ...],
  "atsImprovements": [<string>, ...],
  "learningPath": [
    {"phase": "0-3 Months", "actions": [<string>, ...], "resources": [<string>, ...]},
    {"phase": "3-6 Months", "actions": [<string>, ...], "resources": [<string>, ...]},
    {"phase": "6-12 Months", "actions": [<string>, ...], "resources": [<string>, ...]}
  ]
}`;

    const message = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      max_tokens: 2000,
      messages: [{ role: "user", content: prompt }],
    });

    const raw = message.choices[0].message.content.trim();
    const clean = raw.replace(/^```json|^```|```$/gm, "").trim();
    const data = JSON.parse(clean);

    // ✅ Send email if provided
    if (email) {
      try {
        const gapsList = (data.criticalGaps || []).map(g => `<li>${g}</li>`).join("");
        const pathList = (data.learningPath || []).map((p, i) =>
          `<li><b>${p.phase}</b><ul>${(p.actions || []).map(a => `<li>${a}</li>`).join("")}</ul></li>`
        ).join("");
        await transporter.sendMail({
          from: process.env.EMAIL_USER,
          to: email,
          subject: `StackMatch Results: ${role} (${level})`,
          html: `<h2>Your StackMatch Results</h2>
            <p><b>Role:</b> ${role} — ${level}</p>
            <p><b>Readiness:</b> ${data.readinessScore}/100 — ${data.readinessLabel}</p>
            <p>${data.summary}</p>
            <h3>Critical Gaps</h3><ul>${gapsList}</ul>
            <h3>Learning Path</h3><ul>${pathList}</ul>
            <hr/><small>Generated by StackMatch</small>`,
        });
        data.emailSent = true;
        console.log("Results emailed to:", email);
      } catch (emailErr) {
        console.error("Email failed:", emailErr.message);
        // Don't fail the whole request just because email failed
        data.emailSent = false;
      }
    }

    console.log("Analysis complete for:", role, level);
    res.json(data);
  } catch (err) {
    console.error("Analyze error:", err);
    res.status(500).json({ error: "Analysis failed: " + err.message });
  }
});

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

app.get("/test-email", async (req, res) => {
  try {
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: process.env.EMAIL_USER,
      subject: "Test Email",
      text: "Email is working!",
    });
    res.send("Email sent");
  } catch (err) {
    res.send("Email failed: " + err.message);
  }
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// ✅ Keep-alive AFTER listen, pinging an external service instead
setInterval(() => {
  https.get("https://skill-gap-backend-s5w9.onrender.com/health", (r) => {
    console.log("Keep-alive ping:", r.statusCode);
  }).on("error", (e) => console.log("Ping failed:", e.message));
}, 14 * 60 * 1000);